<div style="background-color:<?php echo $this->bcolor;?>" class="picture-item" id="picture-<?php echo $this->id;?>">
    <div id="picture-toolbar">
	<span id="delete-picture" onclick="clickDeletePicture('picture-<?php echo $this->id;?>')">Delete</span>
    </div>
    <div class="picture-item-caption">
        <span><?php echo $this->caption;?></span>
	<br />
        <span><?php echo $this->original;?></span>
    </div>
    <div class="picture-item-image" onclick="clickPictureItem('picture-<?php echo $this->id;?>')">
    	<span><img src="<?php echo $this->picture; ?>"></span>
    </div>
    <div>
        <span>Any Containers that this Picture Uses Shows Up Here.</span>
    </div>
</div>
