<div style="background-color:<?php echo $this->bcolor;?>" class="wordage-item" id="wordage-<?php echo $this->id;?>">
    <div id="wordage-toolbar">
	<span id="delete-wordage" onclick="clickDeleteWordage('wordage-<?php echo $this->id;?>')">Delete</span>
    </div>
    <div class="wordage-item-title">
        <span><?php echo $this->title;?></span>
	<br />
        <span><?php echo $this->original;?></span>
    </div>
    <div class="wordage-item-text" onclick="clickWordageItemText('wordage-<?php echo $this->id;?>')">
    	<span><?php echo $this->wordage; ?></span>
    </div>
    <div>
        <span>Any Containers That Utilize This Wordage Show Up Here!</span>
        <?php echo(print_r($this->containerItems,true)); ?>
    </div>
</div>
