ContainerType:
    type: entity
    table: containertype
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        containertype:
            type: string 
            nullable: false
            length: 255 
            options:
                fixed: false
    lifecycleCallbacks: {  }
