Correspondent:
    type: entity
    table: correspondent
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        handle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        wordage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        picture:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
        width:
            type: integer
            nullable: false
            options:
                unsigned: false
        height:
            type: integer
            nullable: false
            options:
                unsigned: false
        password:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
