Headline:
    type: entity
    table: headline
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        headline:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        topline:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        usetopline:
            type: boolean
            nullable: false
        fontsize:
            type: integer
            nullable: false
            options:
                unsigned: false
        headlineclass:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        italic:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
