Issue:
    type: entity
    table: issue
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateofpublication:
            type: datetime
            nullable: false
            column: dateOfPublication
        toggledivtagson:
            type: boolean
            nullable: false
            column: toggleDivTagsOn
        priceofcopy:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            column: priceOfCopy
        tagline:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tagLine
        qrimage:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
            column: QRImage
        headingtheme:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: headingTheme
        secondtheme:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: secondTheme
        brace:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
