<div>
	<h2>Content</h2>
	<?php
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('dateofpublication'));
            echo $this->formRow($form->get('toggledivtagson'));
            echo $this->formRow($form->get('priceofcopy'));
            echo $this->formRow($form->get('tagline'));
            echo $this->formRow($form->get('qrimage'));
            echo $this->formRow($form->get('headingtheme'));
            echo $this->formRow($form->get('secondtheme'));
            echo $this->formRow($form->get('brace'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
