<div id="<?php echo $this->pictureid; ?>" class="picture-item"> 
  <script src="/darkroomjs/demo/vendor/fabric.js"></script>
  <script src="/darkroomjs/build/darkroom.js"></script>
  <div id="sometool"><a href="#" onclick="darkr();">Edit</a></div>
  <figure class="image-container target">
      <img id="target" src="<?php echo $this->actualPicture; ?>"/>
      <figcaption class="image-meta">The Caption </figcaption>
  </figure>
</div>
